[package]
name = "eggposting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
megalodon = "0.13.2"
tokio = "1.36.0"
tracing-subscriber = "0.3.18"
